name: bgp-birthday-udagawa-ako
on:
  schedule:
    # xxxx/07/03
    - cron:  '* * 7 3 *'
  workflow_dispatch: ~
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        # Literal body:
        body: "Today is Udagawa Ako's birthday! :tada: -- sent from {{github.repository}}"
        to: kisaragi.effective@gmail.com
        from: Kisaragi.Workflow # <user@example.com>
